"""empty message

Revision ID: 522bf97233a6
Revises: fefe73eb7d0e
Create Date: 2020-05-24 21:29:35.072923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522bf97233a6'
down_revision = 'fefe73eb7d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_project_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_project_id_fkey', 'task', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
