"""empty message

Revision ID: de2c6656510a
Revises: e36ace877204
Create Date: 2020-06-08 00:53:18.786915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2c6656510a'
down_revision = 'e36ace877204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_chunk', 'task_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_chunk', sa.Column('task_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
