"""empty message

Revision ID: e36ace877204
Revises: 130f9fe798ff
Create Date: 2020-06-06 10:21:24.951612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36ace877204'
down_revision = '130f9fe798ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'archived')
    op.drop_column('project', 'archived')
    # ### end Alembic commands ###
