"""empty message

Revision ID: fc9f3a84e5a5
Revises: 
Create Date: 2020-05-24 18:28:03.679053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9f3a84e5a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_chunk', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task_chunk', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_chunk', type_='foreignkey')
    op.drop_column('task_chunk', 'user_id')
    # ### end Alembic commands ###
